version: '3.7' # Versie van de docker compose syntax

services: # Elke service is een docker container, met een eigen doel
  database:
    image: 'postgres:latest'
    container_name: postgres-db
    env_file: # Variabelen in file
      test.env
    volumes: # Lokaal data opslaan anders kwijt na herstart
      - ./db-data/:/var/lib/postgresql/data/
    restart: unless-stopped
    networks:
      - backdb

  backend:
    # Java 20 image
    image: amazoncorretto:20
    container_name: backend
    # Kopieren bestanden van lokaal naar container
    volumes:
      - ./backend.jar:/opt/app/backend.jar
    # Opstarten backend, met profiel
    command: java "-Dspring.profiles.active=prod-postgres" -jar /opt/app/backend.jar
    # Dependencies tussen containers. Helpt met de volgorde van opstarten van containers.
    depends_on:
      - database
    networks:
      - frontback
      - backdb

  frontend:
    image: nginx:latest
    container_name: vue_frontend
    ports: # Poort binnen naar buiten
      - "5001:5001"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend:/usr/share/nginx/html
    restart: always
    depends_on:
      - backend
    networks:
      - frontback

# Opstellen netwerken, zonder netwerken kunnen de containers niet met elkaar praten
# Bridge is de standaard driver om met elkaar te praten.
networks:
  backdb:
    driver: bridge
  frontback:
    driver: bridge